# Build docker image and push to a container registry
parameters:
  name: 'build'
  appName: ''
  vmImageName: ''
  dockerfilePath: ''
  dockerRegistryServiceConnection: ''
  tag: ''

stages:
- stage: ${{ parameters.name }}
  displayName: 'Build and push docker image to container registry'
  jobs:
  - job: run_build
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:
    - task: Docker@2
      displayName: 'Build and push docker image to container registry'
      inputs:
        command: buildAndPush
        repository: ${{ parameters.appName }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
        tags: |
          ${{ parameters.tag }}
